# A set of product items used by external products

set( CALLIGRA_SHOULD_BUILD_PRODUCTS
    SHEETS_PART
    STAGE_PART
    WORDS_PART
    EXTRA_PROPERTIES
    PLUGIN_DEFAULTTOOLS
    PLUGIN_PATHSHAPES
    PLUGIN_VARIABLES
    PLUGIN_CHARTSHAPE
    PLUGIN_PICTURESHAPE
    PLUGIN_TEXTSHAPE
    PLUGIN_PLUGINSHAPE
)
