# A set of product items used by external products

set( CALLIGRA_SHOULD_BUILD_PRODUCTS
    SHEETS_PART
    STAGE_PART
    WORDS_PART
    EXTRA_PROPERTIES
    PLUGIN_DEFAULTTOOLS
    PLUGIN_PATHSHAPES
    PLUGIN_VARIABLES
    PLUGIN_CHARTSHAPE
    PLUGIN_PICTURESHAPE
    PLUGIN_TEXTSHAPE
    PLUGIN_PLUGINSHAPE
    COMPONENTS
    FILTER_DOCX_TO_ODT
    FILTER_DOC_TO_ODT
    FILTER_XLSX_TO_ODS
    FILTER_XLS_TO_SHEETS
    FILTER_PPTX_TO_ODP
    FILTER_PPT_TO_ODP
    FILTER_RTF_TO_ODT
)
